name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        touch .env.development
        echo "${{ secrets.ENV_FILE }}" > .env.development
        npm install

    - name: Install Gulp locally
      run: |
        npm install gulp --save-dev

    - name: Run Gulp
      run: |
        npx gulp
