name: NodeJS with Gulp and Docker

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted  # Ensure this is the correct label for your runner

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Ensure Docker permissions
      run: sudo chmod 666 /var/run/docker.sock

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image using Dockerfile
      run: |
        sudo docker build -t myusername/myapp:${{ github.sha }} .

    - name: Run Docker Compose
      run: |
        sudo docker-compose -f docker-compose.yml up --build -d

    - name: Run Gulp inside Docker container
      run: |
        sudo docker-compose exec <service-name> npx gulp

